# Generated by Django 4.2.1 on 2023-05-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinginfo',
            name='photo',
            field=models.ImageField(upload_to='Media/listing_photos/'),
        ),
    ]
